trigger:
- main
variables:
 buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs: 
    - job: Build
      pool:
       vmImage: windows-latest
      steps:
      - task: UseDotNet@2
        displayName: 'SDK'
        inputs:
          packageType: 'sdk'
          version: '7.0.100'
      - task: NuGetToolInstaller@1
        displayName: 'NuGetTool'
        inputs:
          versionSpec: 
      - task: NuGetCommand@2
        displayName: 'NuGet Restore'
        inputs:
          command: 'restore'
          restoreSolution: '**/*.sln'
      - task: DotNetCoreCLI@2
        displayName: 'Dotnet Restore'
        inputs:
          command: 'restore'
          projects: '**/*.sln'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.sln'
      