trigger:
- main
variables:
 BuildConfiguration: 'Release'

stages:
  - stage: Build
    jobs: 
    - job: Build
      pool:
       vmImage: windows-latest
      steps:
      - task: UseDotNet@2
        displayName: 'SDK'
        inputs:
          packageType: 'sdk'
          version: '7.0.100'
      - task: NuGetToolInstaller@1
        displayName: 'NuGetTool'
        inputs:
          versionSpec: 
      - task: NuGetCommand@2
        displayName: 'NuGet Restore'
        inputs:
          command: 'restore'
          restoreSolution: '**/*.sln'
      - task: DotNetCoreCLI@2
        displayName: 'Dotnet Restore'
        inputs:
          command: 'restore'
          projects: '**/*.sln'
      - task: DotNetCoreCLI@2
        displayName: 'Build project'
        inputs:
          command: 'build'
          projects: '**/*.sln'
          arguments: '--no-restore --configuration Release'
      - task: DotNetCoreCLI@2
        displayName: 'publish'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/*.sln'
          arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
          zipAfterPublish: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          
          
      