trigger:
- main
variables:
 buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs: 
    - job: Build
      pool:
       vmImage: windows-latest
      steps:
      - task: UseDotNet@2
        displayName: 'SDK'
        inputs:
          packageType: 'sdk'
          version: '7.0.100'
      - task: NuGetToolInstaller@1
        displayName: 'NuGetTool'
        inputs:
          versionSpec: 
      - task: NuGetCommand@2
        displayName: 'NuGet Restore'
        inputs:
          command: 'restore'
          restoreSolution: '**/*.sln'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: 'Dotnet Restore'
        inputs:
          command: 'restore'
          projects: '**/*.sln'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: 'Build project'
        inputs:
          command: 'build'
          projects: '**/*.sln'
          arguments: '--configuration $(buildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: 'Publish the project - Release'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/*.sln'
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
         
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        condition: succeeded()



